-- import plugins first
require("plugins")

-- import the rest in arbitrary order
require("general") -- NOTE: should be imported first (leader)
require("buffer")
require("appearance")
require("debugging")
require("file_browsing")
require("folding")
require("generic")
require("highlighting")
require("indentation")
require("integration")
require("restklasse")
require("selection")
require("text_search")
require("language_services")
require("completion")
require("ai_agent")
require("files")
