-- import plugins first
require("plugins")

-- import the rest in arbitrary order
require("appearance")
require("debugging")
require("file_browsing")
require("folding")
require("generic")
require("highlighting")
require("indentation")
require("integration")
require("keybindings")
require("load_and_save")
require("restklasse")
require("selection")
require("text_search")
require("windows")
require("language_services")
require("completion")
